name: 'Test Report'
on:
  workflow_run:
    workflows: ['.NET']                     # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: test-report                  # Name of the check run which will be created
<<<<<<< HEAD
        path: 'HomeWork*/*.xml'                     # Path to test results (inside artifact .zip)
=======
        path: Homework1/TestsCoverage.xml                     # Path to test results (inside artifact .zip)
>>>>>>> 3138edd99bede0d1d6fa0e81a82a07514f3c42c1
        reporter: dotnet-trx              # Format of test results
